gameWidth = 1280
gameHeight = 720
windowWidth, windowHeight = love.graphics.getDimensions()
gameState = "start" 
debugFlag = false 
titleFont = love.graphics.newFont('graphics/fonts/CoffeCake.ttf', 36)
gameOverFont = love.graphics.newFont('graphics/fonts/CoffeCake.ttf', 48)
statFontSmall = love.graphics.newFont('graphics/fonts/Cafe Matcha.ttf', 28)
statFontLarge = love.graphics.newFont('graphics/fonts/CoffeCake.ttf', 36)
musicVolume = .5